# Generated by Django 4.2.16 on 2024-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_comments_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
