# Generated by Django 4.2.16 on 2024-10-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
