# Generated by Django 4.2.16 on 2024-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSiteMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("about", models.TextField()),
            ],
        ),
    ]
