# Generated by Django 4.0.6 on 2024-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_category_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
