# Generated by Django 4.2.16 on 2024-10-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_transaction_base_currency_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
    ]
